version: '3.9'

services:
  csharpapp:
  container_name: 'csharpapp'
  image: myimage/csharpapp:1.0
  build : .
  ports:
    - "8080:80"
    environment:
      ConnectionString_DefaultConnection: "Host=db;Port=5432;Database=postgres;Username=postgres;Password=postgres"
      depends_on:
        - db

  db:
    container_name: 'db'
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

  volumes:
    pgdata: {}
